url: http://trivialdata.org
baseurl:

# Site settings
title: Trivial Data
email: hello@trivialdata.org
description: "Trivial Data is a consulting partnership that focuses on Social Practice, Art, Design, and Technology. The firm was founded by Lisa Ciccarello and Steve Leathers."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Steve Leathers
  pic: 1
  position: Principal Technologist
  social:
    - title: twitter
      url: http://twitter.com/steveleathers
    - title: github
      url: http://github.com/steveleathers
    - title: linkedin
      url: http://linkedin.com/in/steveleathers

- name: Lisa Ciccarello
  pic: 2
  position: Principal Writer
  social:
    - title: twitter
      url: http://twitter.com/salt_lock
    - title: instagram
      url: http://instagram.com/salt_lock
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/trivialdata
  - title: github
    url: http://github.com/TrivialDataOrg

# Postal address (add as many lines as necessary)
address:
  - line: 3732 N Michigan Ave
  - line: Portland, OR 97227

# Build settings
markdown: kramdown
permalink: pretty
