# Site settings
title: TrivialData.org
email: info@trivialdata.org
description: > # this means to ignore newlines until "baseurl:"
  Trivial Data is a consulting partnership that focuses on Social Practice,
  Art, Design, and Technology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://trivialdata.com" # the base hostname & protocol for your site
twitter_username: TrivialData
github_username:  TrivialDataOrg
paginate: 3
permalink: /:title

# Build settings
markdown: kramdown

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Steve Leathers
      layout: "post"
      category: trivial data
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
